services:
  - type: web
    name: ca-dreamers-wa-bot
    env: docker
    plan: starter
    region: singapore
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
